name: ui_effects
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.14
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
